name: mcio-vpt-test
channels:
  - conda-forge
dependencies:
  - python=3.12
  - opencv
  - pip:
    - attrs
    - einops
    - gdown
    - gym==0.23
    - gym3
    - mcio_ctrl
    - opencv-python
    - torch
    - tqdm
    - xvfbwrapper
    - git+https://github.com/jxiong21029/MineCLIP-model
